import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'space-between',
      flexDirection: 'column',
    },
    dragBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 10,
      paddingBottom: 3,
      justifyContent: 'center',
      alignItems: 'center',
    },
    dragBarLine: {
      width: 15,  
      height: 0.5,  
      backgroundColor: '#9F9A9A',
      marginVertical: 1,  
      borderRadius: 0.5,  
    },
    dragBarLineActive: {
      width: 20,
      height: 1,
      backgroundColor: '#000000',
      marginVertical: 2,
      borderRadius: 1,
    },
    editorContainer: {
      position: 'relative',
      backgroundColor: '#ffffff',
      borderRadius: 10,
      margin: 20,
      padding: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      marginBottom: 5,
    },
    // editorContainer: {
    //   flex: 8,
    //   backgroundColor: '#fff',
    //   margin: 20,
    //   borderRadius: 10,
    //   padding: 10,
    //   shadowColor: '#000',
    //   shadowOffset: { width: 0, height: 2 },
    //   shadowOpacity: 0.2,
    //   shadowRadius: 2,
    //   elevation: 2,
    // },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      backgroundColor: '#CBD0D2',
    },
    appendButton: {
      backgroundColor: '#fff',
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
    },
    tabButton: {
      marginHorizontal: 10,
    },
    iconContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 6,
    },
    aiOutputContainer: {
      flex: 2,
      backgroundColor: '#fff',
      margin: 20,
      borderRadius: 10,
      padding: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    aiOutputText: {
      fontSize: 16,
      color: '#333',
    },
    microphoneButton: {
      backgroundColor: '#22AB93',
      borderRadius: 10,
      width: 80,
      height: 25,
      alignItems: 'center',
      justifyContent: 'center',
      margin: 10,
      alignSelf: 'center',
    },
    microphoneButtonText: {
      color: '#fff',
    },
    keyboardAvoidingView: {
      position: 'absolute',
      width: '100%',
      bottom: 0,
    },
    saveButton: {
      backgroundColor: '#6D92CB',
      borderRadius: 10,
      padding: 10,
      width: 80,
      height: 45,
      alignItems: 'center',
      justifyContent: 'center',
      margin: 10,
      alignSelf: 'center',
    },
    saveButtonText: {
      fontSize: 18,
      color: '#fff',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: 'white',
      borderRadius: 10,
      padding: 20,
      width: '80%',
      maxHeight: '80%',
    },
    modalTextInput: {
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 5,
      padding: 10,
      marginBottom: 10,
      maxHeight: 200,
      color: '#000',
    },
    modalButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      backgroundColor: '#22AB93',
      borderRadius: 5,
      padding: 10,
      width: '45%',
      alignItems: 'center',
    },
    modalButtonCancel: {
      backgroundColor: '#EB4335',
      borderRadius: 5,
      padding: 10,
      width: '45%',
      alignItems: 'center',
    },
    modalButtonText: {
      color: 'white',
      fontWeight: 'bold',
    },
    textInputWrapper: {
      flex: 1,
      justifyContent: 'center',
      height: 35, 
    },
    textInput: {
      color: '#000',
      flex: 1,
      height: 30,
      fontSize: 12,
      borderColor: 'gray',
      borderWidth: 1,
      borderRadius: 20,
      paddingHorizontal: 10,
      marginRight: 10,
      backgroundColor: '#D9D9D9',
    },
  });