import { appSchema, tableSchema } from "@nozbe/watermelondb";

export default appSchema({
  version: 76,
  tables: [
    tableSchema({
      name: "folders",
      columns: [
        { name: "name", type: "string" },
        { name: "expanded", type: "boolean" },
        { name: "parent_id", type: "string", isOptional: true },
        { name: 'total_notes', type: 'number' },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "notes",
      columns: [
        { name: "title", type: "string" },
        { name: "content", type: "string" },
        { name: "folder_id", type: "string" },
        { name: "timestamp", type: "number" },
        { name: "edited", type: "boolean" },
        { name: "event_id", type: "string", isOptional: true }, 
        { name: "pinned", type: "boolean", isOptional: true}, 
      ],
    }),
    tableSchema({
      name: "events",
      columns: [
        { name: "title", type: "string" },
        { name: "details", type: "string", isOptional: true },
        { name: "start_date", type: "number", isIndexed: true },
        { name: "start_time", type: "number" },
        { name: "end_date", type: "number", isIndexed: true },
        { name: "end_time", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "google_event_id", type: "string", isOptional: true },
        { name: "source_todo_id", type: "string", isOptional: true, isIndexed: true },
        { name: 'is_google_event', type: 'boolean' }, 
        { name: 'is_todo', type: 'boolean', isOptional: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'home_event_completions',
      columns: [
        { name: 'event_source', type: 'string' },
        { name: 'event_key', type: 'string' },
        { name: 'occurrence_start', type: 'number' },
        { name: 'completed_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'goal_guidance_plans',
      columns: [
        { name: 'goal_id', type: 'string', isIndexed: true },
        { name: 'timeframe', type: 'string' },
        { name: 'deadline', type: 'number' },
        { name: 'feasibility_status', type: 'string' },
        { name: 'feasibility_note', type: 'string' },
        { name: 'alternative_suggestion', type: 'string', isOptional: true },
        { name: 'steps_json', type: 'string' },
        { name: 'active_step_index', type: 'number' },
        { name: 'active_todo_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'active_actions_json', type: 'string', isOptional: true },
        { name: 'completed_step_indexes_json', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'cram', type: 'boolean' },
        { name: 'conversation_json', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'tokens',
      columns: [
        { name: 'access_token', type: 'string' },
        { name: 'expiration_time', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'app_settings',
      columns: [
        { name: 'last_sync_time', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'accounts',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'amazon_username', type: 'string' },
        { name: 'amazon_session_id', type: 'string' },
        { name: 'amazon_email', type: 'string' },
        { name: 'integration_successful', type: 'boolean' },
      ]
    }),
    tableSchema({
      name: 'todos',
      columns: [
        { name: 'text', type: 'string' },
        { name: 'completed', type: 'boolean' },
        { name: 'details', type: 'string', isOptional: true },
        { name: 'due_date', type: 'number', isOptional: true },
        { name: 'has_due_time', type: 'boolean' },
        { name: 'starred', type: 'boolean' },
        { name: 'workspace', type: 'string' },
        { name: 'amazon_url', type: 'string', isOptional: true },
        { name: 'is_amazon_url_loaded', type: 'boolean' },
        { name: 'amazon_url_load_attempts', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'email_id', type: 'string', isOptional: true },
        { name: 'type', type: 'string', isOptional: true },
        { name: 'started_at', type: 'number', isOptional: true },
        { name: 'progress', type: 'number', isOptional: true },
        { name: 'reminder_enabled', type: 'boolean', isOptional: true },
        { name: 'reminder_mode', type: 'string', isOptional: true },
        { name: 'reminder_minutes_before', type: 'number', isOptional: true },
        { name: 'notification_id', type: 'string', isOptional: true },
        { name: 'goal_timeframe', type: 'string', isOptional: true },
        { name: 'task_kind', type: 'string', isOptional: true },
        { name: 'guidance_path', type: 'string', isOptional: true },
        { name: 'goal_behavior_json', type: 'string', isOptional: true },
        { name: 'sort_scope', type: 'string', isOptional: true },
        { name: 'sort_order', type: 'number', isOptional: true },
        { name: 'planned_duration_minutes', type: 'number', isOptional: true },
        { name: 'recurrence_series_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'recurrence_occurrence_date', type: 'number', isOptional: true, isIndexed: true },
        { name: 'recurrence_override', type: 'boolean', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'todo_recurrence_series',
      columns: [
        { name: 'unit', type: 'string' },
        { name: 'interval', type: 'number' },
        { name: 'start_date', type: 'number' },
        { name: 'anchor_day', type: 'number', isOptional: true },
        { name: 'active', type: 'boolean' },
        { name: 'skipped_dates_json', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'user_preferences',
      columns: [
        { name: 'workspace_name', type: 'string' },
        { name: 'display_name', type: 'string', isOptional: true },
        { name: 'original_name', type: 'string', isOptional: true },
        { name: 'color', type: 'string' },
        { name: 'todo_type', type: 'string', isOptional: true },
      ]
    }),
    tableSchema({
      name: 'emails',
      columns: [
        { name: 'from', type: 'string' },
        { name: 'subject', type: 'string' },
        { name: 'body', type: 'string' },  
        { name: 'snippet', type: 'string', isOptional: true },
        { name: 'gmail_id', type: 'string' },
        { name: 'email_date', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ]
    }),
    tableSchema({
      name: 'chat_sessions',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'summary', type: 'string', isOptional: true },
        { name: 'pinned', type: 'boolean' },
        { name: 'last_message_at', type: 'number', isOptional: true },
        { name: 'title_manually_set', type: 'boolean', isOptional: true },
        { name: 'title_generated_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'chat_messages',
      columns: [
        { name: 'session_id', type: 'string', isIndexed: true },
        { name: 'role', type: 'string' },
        { name: 'content', type: 'string', isOptional: true },
        { name: 'card_json', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'recipe_guides',
      columns: [
        { name: 'todo_id', type: 'string', isIndexed: true },
        { name: 'answers_json', type: 'string' },
        { name: 'videos_json', type: 'string' },
        { name: 'selected_video_json', type: 'string' },
        { name: 'ingredients_json', type: 'string' },
        { name: 'equipment_json', type: 'string' },
        { name: 'steps_json', type: 'string' },
        { name: 'conversation_json', type: 'string' },
        { name: 'active_step_index', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'transcript_language', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'task_guides',
      columns: [
        { name: 'todo_id', type: 'string', isIndexed: true },
        { name: 'steps_json', type: 'string' },
        { name: 'conversation_json', type: 'string' },
        { name: 'active_step_index', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'skill_guides',
      columns: [
        { name: 'todo_id', type: 'string', isIndexed: true },
        { name: 'videos_json', type: 'string' },
        { name: 'selected_video_json', type: 'string' },
        { name: 'steps_json', type: 'string' },
        { name: 'conversation_json', type: 'string' },
        { name: 'active_step_index', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'transcript_language', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
